export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';


export const PURCHASE_INT  = 'PURCHASE_INT'

export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'

export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED'